### ISSUE TITLE
Importing Vue components with Rollup

### ISSUE THREAD

**Issue by CrashyBang** [kazupon/vue-cli-plugin-p11n#19]
I am trying to setup a install a Vue component like so:

```js
import Search from "./components/Search.vue";

const version = "__VERSION__";

const install = Vue => {
    Vue.component(Search.name, Search);
};

const plugin = {
  install,
  version
};

export default plugin;

if (typeof window !== "undefined" && window.Vue) {
  window.Vue.use(plugin);
}
```

However when I try to build (`npm run build`) I get the following output:
```
Building for production mode as plugin ...
 ERROR  Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (.../module-search/node_modules/rollup/dist/rollup.js:3601:30)
    at Module.error (.../module-search/node_modules/rollup/dist/rollup.js:14477:9)
    at tryParse (.../module-search/node_modules/rollup/dist/rollup.js:14397:16)
    at Module.setSource (.../module-search/node_modules/rollup/dist/rollup.js:14671:35)
    at .../module-search/node_modules/rollup/dist/rollup.js:17836:20
 ERROR  Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (.../module-search/node_modules/rollup/dist/rollup.js:3601:30)
    at Module.error (.../module-search/node_modules/rollup/dist/rollup.js:14477:9)
    at tryParse (.../module-search/node_modules/rollup/dist/rollup.js:14397:16)
    at Module.setSource (.../module-search/node_modules/rollup/dist/rollup.js:14671:35)
    at .../module-search/node_modules/rollup/dist/rollup.js:17836:20
 ERROR  Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (.../module-search/node_modules/rollup/dist/rollup.js:3601:30)
    at Module.error (.../module-search/node_modules/rollup/dist/rollup.js:14477:9)
    at tryParse (.../module-search/node_modules/rollup/dist/rollup.js:14397:16)
    at Module.setSource (.../module-search/node_modules/rollup/dist/rollup.js:14671:35)
    at .../module-search/node_modules/rollup/dist/rollup.js:17836:20
 ERROR  Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (.../module-search/node_modules/rollup/dist/rollup.js:3601:30)
    at Module.error (.../module-search/node_modules/rollup/dist/rollup.js:14477:9)
    at tryParse (.../module-search/node_modules/rollup/dist/rollup.js:14397:16)
    at Module.setSource (.../module-search/node_modules/rollup/dist/rollup.js:14671:35)
    at .../module-search/node_modules/rollup/dist/rollup.js:17836:20
```

After reading some of the other issues I think I may need [rollup-plugin-vue](https://github.com/vuejs/rollup-plugin-vue) but I am not entirely sure how to integrate this.

 Cheers!

**Comment by EtienneSchmitz** [comment]
Hello.

Same problem with my programm.
The Vue file did not parse and I solved the problem by adding [https://github.com/vuejs/rollup-plugin-vue](rollup-plugin-vue) during the compiling time.

I suggest a PR.

Cheers !

**Comment by kazupon** [comment]
I've released v0.2.1

**Comment by klarkc** [comment]
Still happening in v0.2.1:

```
 ERROR  Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/walker/Sources/ic-vslider/node_modules/rollup/dist/rollup.js:3598:30)
    at Module.error (/home/walker/Sources/ic-vslider/node_modules/rollup/dist/rollup.js:14470:9)
    at tryParse (/home/walker/Sources/ic-vslider/node_modules/rollup/dist/rollup.js:14390:16)
    at Module.setSource (/home/walker/Sources/ic-vslider/node_modules/rollup/dist/rollup.js:14664:35)
    at /home/walker/Sources/ic-vslider/node_modules/rollup/dist/rollup.js:17837:20
```

relevant package.json
```json
{
  "name": "ic-vslider",
  "version": "0.1.0",
  "scripts": {
    "build": "vue-cli-service build",
  },
  "dependencies": {
    "core-js": "^2.6.5",
    "swiper": "^4.5.0",
    "vue": "^2.6.6",
    "vue-awesome-swiper": "^3.1.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.5.0",
    "@vue/cli-plugin-eslint": "^3.5.0",
    "@vue/cli-plugin-unit-jest": "^3.5.0",
    "@vue/cli-service": "^3.5.0",
    "@vue/eslint-config-airbnb": "^4.0.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.6.0",
    "eslint": "^5.8.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-cli-plugin-p11n": "^0.2.1",
    "vue-template-compiler": "^2.5.21",
    "vuepress-jsdoc": "^1.7.0"
  }
}
```

index.js
```js
import IcVsliderSlide from './components/ic-vslider-slide.vue';
import IcVslider from './components/ic-vslider.vue';


const version = '__VERSION__';

const install = (Vue) => {
  /*
   * NOTE:
   *   if you need to extend Vue contstructor, you can extend it in here.
   */

  Vue.component(IcVsliderSlide.name, IcVsliderSlide);
  Vue.component(IcVslider.name, IcVslider);

  /*
   * NOTE:
   *  somthing implementation here ...
   */
};

const plugin = {
  install,
  version,
};

export default plugin;

if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(plugin);
}
```

**Comment by sts-ryan-holton** [comment]
@kazupon Still not working on `0.2.1`, `0.3.0` and `0.4.0`, my `plugin.js` file is:

```js
/*
 * NOTE:
 *   This file is plugin stub for main.js
 */

import Vue from 'vue'
import VueResource from 'vue-resource'
import { ValidationProvider, ValidationObserver, extend, configure } from 'vee-validate';
import * as rules from 'vee-validate/dist/rules';

const config = {
  classes: {
    valid: '',
    invalid: 'is-danger'
  }
};

configure(config);

Object.keys(rules).forEach(rule => {
  extend(rule, rules[rule]);
});

// Register it globally
Vue.component("validation-observer", ValidationObserver);
Vue.component("validation-provider", ValidationProvider);

import plugin from './index'

Vue.use(VueResource)
Vue.use(plugin)

/*
 * NOTE:
 *   If you want Vue instance of main.js to import something in your plugin as a Vue option,
 *   you need to export it here.
 */
// export default plugin
```
